/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_creditease_toumi_AdjustApi */

#ifndef _Included_com_creditease_toumi_AdjustApi
#define _Included_com_creditease_toumi_AdjustApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_creditease_toumi_AdjustApi
 * Method:    init
 * Signature: (I[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_com_creditease_toumi_AdjustApi_init
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     com_creditease_toumi_AdjustApi
 * Method:    reloadModel
 * Signature: (I[D[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_com_creditease_toumi_AdjustApi_reloadModel
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     com_creditease_toumi_AdjustApi
 * Method:    run
 * Signature: (D[D[D)V
 */
JNIEXPORT void JNICALL Java_com_creditease_toumi_AdjustApi_run
  (JNIEnv *, jobject, jdouble, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
